version: '3'

services:
  # Basic Streamlit app
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - APP_FILE=app.py
    restart: unless-stopped

  # Enhanced Streamlit app with advanced features
  enhanced:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./results:/app/results
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - APP_FILE=enhanced_app.py
    restart: unless-stopped
